//    uniCenta oPOS - Touch Friendly Point Of Sale
//    Copyright (c) 2009-2018 uniCenta & previous Openbravo POS works
//    https://unicenta.com
//
//    This file is part of uniCenta oPOS
//
//    uniCenta oPOS is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    uniCenta oPOS is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with uniCenta oPOS.  If not, see <http://www.gnu.org/licenses/>.

report = new com.unicenta.pos.reports.PanelReportBean();

report.setTitleKey("Menu.ProductSales");
report.setReport("/com/unicenta/reports/sales_chart_pro_test");
report.setResourceBundle("com/unicenta/reports/sales_messages");

report.setSentence(
            "SELECT " +
            "products.REFERENCE, " +
            "products.NAME, " +
            "SUM(ticketlines.UNITS) AS UNITS, " +
            "SUM(ticketlines.UNITS * ticketlines.PRICE) AS TOTAL " +
            "FROM receipts, tickets, ticketlines, products " +
            "WHERE receipts.ID = tickets.ID AND tickets.ID = ticketlines.TICKET AND ticketlines.PRODUCT = products.ID AND ?(QBF_FILTER) " +
            "GROUP BY products.REFERENCE, products.NAME " +
            "ORDER BY products.NAME");

report.addParameter("receipts.DATENEW");
report.addParameter("receipts.DATENEW");

paramdates = new com.unicenta.pos.reports.JParamsDatesInterval();

paramdates.setStartDate(com.unicenta.beans.DateUtils.getToday());
// JG - 8 Jan 14 paramdates.setEndDate(com.unicenta.beans.DateUtils.getToday());
paramdates.setEndDate(com.unicenta.beans.DateUtils.getTodayMinutes());

report.addQBFFilter(paramdates);
report.addParameter("products.NAME");
report.addParameter("products.PRICEBUY");
report.addParameter("products.PRICESELL");
report.addParameter("products.CATEGORY");
report.addParameter("products.CODE");
report.addQBFFilter(new com.unicenta.pos.ticket.ProductFilter());

report.addField("REFERENCE", com.unicenta.data.loader.Datas.STRING);
report.addField("NAME", com.unicenta.data.loader.Datas.STRING);
report.addField("UNITS", com.unicenta.data.loader.Datas.DOUBLE);
report.addField("TOTAL", com.unicenta.data.loader.Datas.DOUBLE);

report;

